// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// pmvnorm2
double pmvnorm2();
RcppExport SEXP extpkg_pmvnorm2() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(pmvnorm2());
    return __result;
END_RCPP
}
