// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __cpptests_h__
#define __cpptests_h__

#include "cpptests_RcppExports.h"

#endif // __cpptests_h__
