# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
exp_func <- function() {
    .Call('cpptests_exp_func', PACKAGE = 'cpptests')
}

pmvnorm <- function(lls, uls, mu, sigma) {
    .Call('cpptests_pmvnorm', PACKAGE = 'cpptests', lls, uls, mu, sigma)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('cpptests_RcppExport_registerCCallable', PACKAGE = 'cpptests')
})
